language: python
cache: pip
python:
- '2.7'
- '3.3'
- '3.4'
- '3.5'
install: pip install . mock nose pylint
script:
- nosetests
- pylint envopt
deploy:
  provider: pypi
  user: amancevice
  password:
    secure: hH9HHXlMwEmjOnexUeI7FeYmWJpO8G5IXxlZkaVrWrn4wt+s3C7iHJmn0me7QQQrLorn/0Z28tBL29HTNIDFv5f+/p+JRs5dXlqvHcjR1qiHc17H50GIg4Vqki6j1Ikh9Rhd4069oRTX4KCXC8GBLJpruM//2PnmTNcyLSLToB7OiQuayhqd7X1R/pUGk3LbOmHtRXUqXVU3LPY6ScCq2RnaCOnpzRSWPE6sZjaFMqF9h4YLwiDAxeTpr71jzC+PR+md8haBwzuwb8Z9rf93BFRMf7gH2FLkUj1EN0dv3aSeynJ84/aaGf4XgTeYnBd8BKaSaELf9SHE6Qy3MnNgAqzJnyIahu/ml9CfV6eMa5kdmU7LSrKC0kCrdtxpxibGrLQsngHLc+bf68FAAZ4IRgjydf+sirdEhl9ysxiesCqZRaMdNQ0YkQhIaoL1SnhgUjBWSP0SZFznGUs2radZIAnBwKCdNA6XziLHGGwNs5oYQY0TAL4NsJR0pGToZSbFbuz4EsgjjrNmeirImHIiQmKHgshauGQfI7zSTR8QkkMrSUrw6MNy7CNUS/zADdg27pxLHAKmt3BEgI0V5jGJuNcuEHE2ZZ+yvam1Py/YuLEAZm5X8ar5tq6F89Fxka3/G/xCVbb8aA70WtcfWdOoGZil4TDYxPJEo6dlbH4YlnY=
  on:
    tags: true
    repo: amancevice/envopt
